#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_BACKEND.DbConnect
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KPI_DataB")]
	public partial class DbConnectDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DbConnectDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbConnectDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbConnectDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbConnectDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.rpt_kpiWithOrgCode")]
		public ISingleResult<rpt_kpiWithOrgCodeResult> rpt_kpiWithOrgCode()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<rpt_kpiWithOrgCodeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spKPIGetData_from_AStaff")]
		public ISingleResult<spKPIGetData_from_AStaffResult> spKPIGetData_from_AStaff([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YYYY", DbType="NVarChar(4)")] string yYYY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MM", DbType="NVarChar(2)")] string mM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORGCODE", DbType="NVarChar(4)")] string oRGCODE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yYYY, mM, oRGCODE);
			return ((ISingleResult<spKPIGetData_from_AStaffResult>)(result.ReturnValue));
		}
	}
	
	public partial class rpt_kpiWithOrgCodeResult
	{
		
		private System.Nullable<int> _OrgLevel;
		
		private string _OrgCode;
		
		private string _OrgName;
		
		private string _YYYY;
		
		private string _MM;
		
		private System.Nullable<int> _KPIOrder;
		
		private string _KPICode;
		
		private string _KPIBullet;
		
		private string _KPIName;
		
		private string _KPILink;
		
		private string _Unit;
		
		private System.Nullable<int> _UnitDivider;
		
		private System.Nullable<bool> _HasValue;
		
		private System.Nullable<bool> _IsCountryLevel;
		
		private string _Description;
		
		private System.Nullable<double> _TargetMonth;
		
		private System.Nullable<double> _ActualMonth;
		
		private System.Nullable<int> _NoOfDecimalTarget;
		
		private System.Nullable<int> _NoOfDecimalActual;
		
		private System.Nullable<int> _MeasureType;
		
		private string _OrgOwnerCode;
		
		private string _OrgOwner;
		
		private string _Officer;
		
		private string _Tel;
		
		private string _EMail;
		
		private System.Nullable<int> _Weight;
		
		private System.Nullable<double> _FirstScore;
		
		private System.Nullable<double> _FinalScore;
		
		private System.Nullable<int> _StatusColor;
		
		private string _LastDataDate;
		
		public rpt_kpiWithOrgCodeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgLevel", DbType="Int")]
		public System.Nullable<int> OrgLevel
		{
			get
			{
				return this._OrgLevel;
			}
			set
			{
				if ((this._OrgLevel != value))
				{
					this._OrgLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgCode", DbType="NVarChar(500)")]
		public string OrgCode
		{
			get
			{
				return this._OrgCode;
			}
			set
			{
				if ((this._OrgCode != value))
				{
					this._OrgCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgName", DbType="NVarChar(500)")]
		public string OrgName
		{
			get
			{
				return this._OrgName;
			}
			set
			{
				if ((this._OrgName != value))
				{
					this._OrgName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YYYY", DbType="NVarChar(500)")]
		public string YYYY
		{
			get
			{
				return this._YYYY;
			}
			set
			{
				if ((this._YYYY != value))
				{
					this._YYYY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MM", DbType="NVarChar(500)")]
		public string MM
		{
			get
			{
				return this._MM;
			}
			set
			{
				if ((this._MM != value))
				{
					this._MM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPIOrder", DbType="Int")]
		public System.Nullable<int> KPIOrder
		{
			get
			{
				return this._KPIOrder;
			}
			set
			{
				if ((this._KPIOrder != value))
				{
					this._KPIOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPICode", DbType="NVarChar(500)")]
		public string KPICode
		{
			get
			{
				return this._KPICode;
			}
			set
			{
				if ((this._KPICode != value))
				{
					this._KPICode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPIBullet", DbType="NVarChar(500)")]
		public string KPIBullet
		{
			get
			{
				return this._KPIBullet;
			}
			set
			{
				if ((this._KPIBullet != value))
				{
					this._KPIBullet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPIName", DbType="NVarChar(500)")]
		public string KPIName
		{
			get
			{
				return this._KPIName;
			}
			set
			{
				if ((this._KPIName != value))
				{
					this._KPIName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPILink", DbType="NVarChar(500)")]
		public string KPILink
		{
			get
			{
				return this._KPILink;
			}
			set
			{
				if ((this._KPILink != value))
				{
					this._KPILink = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(500)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitDivider", DbType="Int")]
		public System.Nullable<int> UnitDivider
		{
			get
			{
				return this._UnitDivider;
			}
			set
			{
				if ((this._UnitDivider != value))
				{
					this._UnitDivider = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasValue", DbType="Bit")]
		public System.Nullable<bool> HasValue
		{
			get
			{
				return this._HasValue;
			}
			set
			{
				if ((this._HasValue != value))
				{
					this._HasValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCountryLevel", DbType="Bit")]
		public System.Nullable<bool> IsCountryLevel
		{
			get
			{
				return this._IsCountryLevel;
			}
			set
			{
				if ((this._IsCountryLevel != value))
				{
					this._IsCountryLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetMonth", DbType="Float")]
		public System.Nullable<double> TargetMonth
		{
			get
			{
				return this._TargetMonth;
			}
			set
			{
				if ((this._TargetMonth != value))
				{
					this._TargetMonth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualMonth", DbType="Float")]
		public System.Nullable<double> ActualMonth
		{
			get
			{
				return this._ActualMonth;
			}
			set
			{
				if ((this._ActualMonth != value))
				{
					this._ActualMonth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfDecimalTarget", DbType="Int")]
		public System.Nullable<int> NoOfDecimalTarget
		{
			get
			{
				return this._NoOfDecimalTarget;
			}
			set
			{
				if ((this._NoOfDecimalTarget != value))
				{
					this._NoOfDecimalTarget = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfDecimalActual", DbType="Int")]
		public System.Nullable<int> NoOfDecimalActual
		{
			get
			{
				return this._NoOfDecimalActual;
			}
			set
			{
				if ((this._NoOfDecimalActual != value))
				{
					this._NoOfDecimalActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureType", DbType="Int")]
		public System.Nullable<int> MeasureType
		{
			get
			{
				return this._MeasureType;
			}
			set
			{
				if ((this._MeasureType != value))
				{
					this._MeasureType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgOwnerCode", DbType="NVarChar(500)")]
		public string OrgOwnerCode
		{
			get
			{
				return this._OrgOwnerCode;
			}
			set
			{
				if ((this._OrgOwnerCode != value))
				{
					this._OrgOwnerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgOwner", DbType="NVarChar(500)")]
		public string OrgOwner
		{
			get
			{
				return this._OrgOwner;
			}
			set
			{
				if ((this._OrgOwner != value))
				{
					this._OrgOwner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Officer", DbType="NVarChar(500)")]
		public string Officer
		{
			get
			{
				return this._Officer;
			}
			set
			{
				if ((this._Officer != value))
				{
					this._Officer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(500)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(500)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int")]
		public System.Nullable<int> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstScore", DbType="Float")]
		public System.Nullable<double> FirstScore
		{
			get
			{
				return this._FirstScore;
			}
			set
			{
				if ((this._FirstScore != value))
				{
					this._FirstScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalScore", DbType="Float")]
		public System.Nullable<double> FinalScore
		{
			get
			{
				return this._FinalScore;
			}
			set
			{
				if ((this._FinalScore != value))
				{
					this._FinalScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusColor", DbType="Int")]
		public System.Nullable<int> StatusColor
		{
			get
			{
				return this._StatusColor;
			}
			set
			{
				if ((this._StatusColor != value))
				{
					this._StatusColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDataDate", DbType="NVarChar(500)")]
		public string LastDataDate
		{
			get
			{
				return this._LastDataDate;
			}
			set
			{
				if ((this._LastDataDate != value))
				{
					this._LastDataDate = value;
				}
			}
		}
	}
	
	public partial class spKPIGetData_from_AStaffResult
	{
		
		private System.Nullable<int> _OrgLevel;
		
		private string _OrgCode;
		
		private string _OrgName;
		
		private string _YYYY;
		
		private string _MM;
		
		private System.Nullable<int> _KPIOrder;
		
		private string _KPICode;
		
		private string _KPIBullet;
		
		private string _KPIName;
		
		private string _KPILink;
		
		private string _Unit;
		
		private System.Nullable<int> _UnitDivider;
		
		private System.Nullable<bool> _HasValue;
		
		private System.Nullable<bool> _IsCountryLevel;
		
		private string _Description;
		
		private System.Nullable<double> _TargetMonth;
		
		private System.Nullable<double> _ActualMonth;
		
		private System.Nullable<int> _NoOfDecimalTarget;
		
		private System.Nullable<int> _NoOfDecimalActual;
		
		private System.Nullable<int> _MeasureType;
		
		private string _OrgOwnerCode;
		
		private string _OrgOwner;
		
		private string _Officer;
		
		private string _Tel;
		
		private string _EMail;
		
		private System.Nullable<int> _Weight;
		
		private System.Nullable<double> _FirstScore;
		
		private System.Nullable<double> _FinalScore;
		
		private System.Nullable<int> _StatusColor;
		
		private string _LastDataDate;
		
		public spKPIGetData_from_AStaffResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgLevel", DbType="Int")]
		public System.Nullable<int> OrgLevel
		{
			get
			{
				return this._OrgLevel;
			}
			set
			{
				if ((this._OrgLevel != value))
				{
					this._OrgLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgCode", DbType="NVarChar(500)")]
		public string OrgCode
		{
			get
			{
				return this._OrgCode;
			}
			set
			{
				if ((this._OrgCode != value))
				{
					this._OrgCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgName", DbType="NVarChar(500)")]
		public string OrgName
		{
			get
			{
				return this._OrgName;
			}
			set
			{
				if ((this._OrgName != value))
				{
					this._OrgName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YYYY", DbType="NVarChar(500)")]
		public string YYYY
		{
			get
			{
				return this._YYYY;
			}
			set
			{
				if ((this._YYYY != value))
				{
					this._YYYY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MM", DbType="NVarChar(500)")]
		public string MM
		{
			get
			{
				return this._MM;
			}
			set
			{
				if ((this._MM != value))
				{
					this._MM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPIOrder", DbType="Int")]
		public System.Nullable<int> KPIOrder
		{
			get
			{
				return this._KPIOrder;
			}
			set
			{
				if ((this._KPIOrder != value))
				{
					this._KPIOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPICode", DbType="NVarChar(500)")]
		public string KPICode
		{
			get
			{
				return this._KPICode;
			}
			set
			{
				if ((this._KPICode != value))
				{
					this._KPICode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPIBullet", DbType="NVarChar(500)")]
		public string KPIBullet
		{
			get
			{
				return this._KPIBullet;
			}
			set
			{
				if ((this._KPIBullet != value))
				{
					this._KPIBullet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPIName", DbType="NVarChar(500)")]
		public string KPIName
		{
			get
			{
				return this._KPIName;
			}
			set
			{
				if ((this._KPIName != value))
				{
					this._KPIName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPILink", DbType="NVarChar(500)")]
		public string KPILink
		{
			get
			{
				return this._KPILink;
			}
			set
			{
				if ((this._KPILink != value))
				{
					this._KPILink = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(500)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitDivider", DbType="Int")]
		public System.Nullable<int> UnitDivider
		{
			get
			{
				return this._UnitDivider;
			}
			set
			{
				if ((this._UnitDivider != value))
				{
					this._UnitDivider = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasValue", DbType="Bit")]
		public System.Nullable<bool> HasValue
		{
			get
			{
				return this._HasValue;
			}
			set
			{
				if ((this._HasValue != value))
				{
					this._HasValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCountryLevel", DbType="Bit")]
		public System.Nullable<bool> IsCountryLevel
		{
			get
			{
				return this._IsCountryLevel;
			}
			set
			{
				if ((this._IsCountryLevel != value))
				{
					this._IsCountryLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetMonth", DbType="Float")]
		public System.Nullable<double> TargetMonth
		{
			get
			{
				return this._TargetMonth;
			}
			set
			{
				if ((this._TargetMonth != value))
				{
					this._TargetMonth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualMonth", DbType="Float")]
		public System.Nullable<double> ActualMonth
		{
			get
			{
				return this._ActualMonth;
			}
			set
			{
				if ((this._ActualMonth != value))
				{
					this._ActualMonth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfDecimalTarget", DbType="Int")]
		public System.Nullable<int> NoOfDecimalTarget
		{
			get
			{
				return this._NoOfDecimalTarget;
			}
			set
			{
				if ((this._NoOfDecimalTarget != value))
				{
					this._NoOfDecimalTarget = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfDecimalActual", DbType="Int")]
		public System.Nullable<int> NoOfDecimalActual
		{
			get
			{
				return this._NoOfDecimalActual;
			}
			set
			{
				if ((this._NoOfDecimalActual != value))
				{
					this._NoOfDecimalActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureType", DbType="Int")]
		public System.Nullable<int> MeasureType
		{
			get
			{
				return this._MeasureType;
			}
			set
			{
				if ((this._MeasureType != value))
				{
					this._MeasureType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgOwnerCode", DbType="NVarChar(500)")]
		public string OrgOwnerCode
		{
			get
			{
				return this._OrgOwnerCode;
			}
			set
			{
				if ((this._OrgOwnerCode != value))
				{
					this._OrgOwnerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgOwner", DbType="NVarChar(500)")]
		public string OrgOwner
		{
			get
			{
				return this._OrgOwner;
			}
			set
			{
				if ((this._OrgOwner != value))
				{
					this._OrgOwner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Officer", DbType="NVarChar(500)")]
		public string Officer
		{
			get
			{
				return this._Officer;
			}
			set
			{
				if ((this._Officer != value))
				{
					this._Officer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(500)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(500)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int")]
		public System.Nullable<int> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstScore", DbType="Float")]
		public System.Nullable<double> FirstScore
		{
			get
			{
				return this._FirstScore;
			}
			set
			{
				if ((this._FirstScore != value))
				{
					this._FirstScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalScore", DbType="Float")]
		public System.Nullable<double> FinalScore
		{
			get
			{
				return this._FinalScore;
			}
			set
			{
				if ((this._FinalScore != value))
				{
					this._FinalScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusColor", DbType="Int")]
		public System.Nullable<int> StatusColor
		{
			get
			{
				return this._StatusColor;
			}
			set
			{
				if ((this._StatusColor != value))
				{
					this._StatusColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDataDate", DbType="NVarChar(500)")]
		public string LastDataDate
		{
			get
			{
				return this._LastDataDate;
			}
			set
			{
				if ((this._LastDataDate != value))
				{
					this._LastDataDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
